export const DEFAULT_BUCKET_NAME = '__BUCKET-STORAGE__';

export const DEFAULT_ENCRYPTION_KEY = '1234123412ABCDEF';

export  const ENCRYPT_TEXT_SYMBOL = '@BUCKET-STORAGE'

export const BUCKET_STORAGE_KEY = '__BUCKET_STORAGE_KEYS__';